# Generated by Django 3.0.2 on 2020-01-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_traffic'),
    ]

    operations = [
        migrations.AddField(
            model_name='traffic',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='traffic',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='traffic',
            name='timezone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
