# Generated by Django 3.0.2 on 2020-01-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200117_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='traffic',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
